### ISSUE TITLE
Is there a way to open the program without opening my web browser?

### ISSUE THREAD

**Issue by cor094** [mikew/xarcade-xinput#11]
I plan on using my phone to control the Web UI. As a result, I do not need my PC browser to open up whenever I load the program.  Is it possible? Thanks! - Cory

**Comment by mikew** [comment]
Yep! You can launch it with `XArcade XInput.exe --skip-ui`.

**Comment by cor094** [comment]
Thanks! You rock! .. and this program is great.  Was able to get it set up to play Streets of Rage 4 on a 4-player cabinet.

**Comment by cor094** [comment]
Sorry for all the questions. Is there a list anywhere of other flags or commands that are available. Specifically,  I'm interested in launching the program without it being in an "enabled" state. Additionally, I was wondering if it is possible to enable/disable via command-line or load a specific mapping via command-line. Thanks! - Cory

**Comment by mikew** [comment]
This is the closest thing to a list of all flags available: https://github.com/mikew/xarcade-xinput/blob/c18b7b5881733cb9f1e57295c94b65f1c645a830/XArcade%20XInput/Program.cs#L12-L22

There's no way to start it disabled, but that's a great idea.

And since it's backed by a rest server, it's all possible from a command line. I should really add it to the readme.

Here's enabling / disabling: https://github.com/mikew/xarcade-xinput/issues/10#issuecomment-452343222

Changing mappings is also possible in a similar manor, off the top of my head I think it would be:

```powershell
Invoke-RestMethod -Method Post -Uri http://localhost:32123/api/keyboard/mapping/current -Body "Mapping Name As Appears In The Web UI"
```

**Comment by cor094** [comment]
Worked great! Thanks!

**Comment by mikew** [comment]
Great! I've created an issue about the ability to start in a disabled state here https://github.com/mikew/xarcade-xinput/issues/12.
